---
django_environment:
    DEBUG: true
    ADMINS: James Turk james@openstates.org
    BOUNDARY_SERVICE_URL: http://geo.openstates.org/
    SECRET_KEY: "{{ lookup('credstash', 'site.SECRET_KEY') }}"
    EMAIL_HOST: email-smtp.us-east-1.amazonaws.com
    EMAIL_HOST_USER: "{{ lookup('credstash', 'site.EMAIL_HOST_USER') }}"
    EMAIL_HOST_PASSWORD: "{{ lookup('credstash', 'site.EMAIL_HOST_PASSWORD') }}"
    DATABASE_URL: "{{ lookup('credstash', 'site.DATABASE_URL') }}"
    # STRIPE_PUBLIC_KEY: "{{ lookup('credstash', 'site.STRIPE_PUBLIC_KEY') }}"
    # STRIPE_SECRET_KEY: "{{ lookup('credstash', 'site.STRIPE_SECRET_KEY') }}"
    # RAVEN_DSN: "{{ lookup('credstash', 'site.RAVEN_DSN') }}"

newrelic_key: "{{ lookup('credstash', 'newrelic.INI_KEY') }}" 
server_name: alpha.openstates.org
# ssl_cert: /etc/letsencrypt/live/openstates.org/fullchain.pem
# ssl_key: /etc/letsencrypt/live/openstates.org/privkey.pem
internal_geo_ip: "{{ lookup('credstash', 'site.INTERNAL_GEO_IP') }}"
