---
- name: install system packages
  apt:
    update_cache: yes
    pkg:
      - build-essential
      - git
      - mercurial
      - python-pycurl
      - python-boto
      - libpq-dev
      - unzip
      - gdal-bin
      - python
      - python-dev
      - virtualenv
      - uwsgi
      - nginx
      - uwsgi-plugin-python3
      - libxslt-dev
      - letsencrypt
- name: add localhost alias
  lineinfile: dest=/etc/hosts line='127.0.0.1 alpha.openstates.org'
- name: make project dir
  file: path=/home/openstates state=directory
- name: add project user
  user: name=openstates home=/home/openstates shell=/bin/bash state=present
- name: chown user directory
  file: path=/home/openstates owner=openstates
- name: add user subdirectories
  file: path=/home/openstates/{{item}} owner=openstates state=directory
  with_items:
    - letsencrypt
  become_user: "openstates"
- name: add env_vars for project user
  template: src=env_vars.j2 dest=/home/openstates/env_vars mode=640
  become_user: "openstates"

# letsencrypt
- name: add letsencrypt renewal crontab
  cron: job="letsencrypt renew" special_time="daily" name="renew certificate"
- name: restart nginx weekly
  cron: job="systemctl restart nginx" special_time="weekly" name="restart nginx"
# - name: archive letsencrypt stuff
#   cron: job='bash -c "tar cvf /tmp/le$(date +\%Y\%m\%d).gz /etc/letsencrypt/ && aws s3 cp /tmp/le$(date +\%Y\%m\%d).gz s3://openstates-backups/letsencrypt/ && rm /tmp/le$(date +\%Y\%m\%d).gz"' special_time="monthly" name="backup letsencrypt"

# virtualenv
- name: checkout project directories
  git: repo=https://github.com/openstates/new-openstates.org.git dest=/home/openstates/src/openstates.org accept_hostkey=yes version=develop
  become_user: "openstates"
  notify:
    - restart django-application
  register: gitresult
- name: create virtualenv
  command: virtualenv -p python3.6 /home/openstates/virt{{ gitresult.after }}
  become_user: "openstates"
  notify:
    - restart django-application
- name: add checkouts to python path
  lineinfile: dest=/home/openstates/virt{{ gitresult.after }}/lib/python3.6/site-packages/checkouts.pth create=yes state=present line=/home/openstates/src/openstates.org
  become_user: "openstates"
- name: install pipenv
  pip: name=pipenv virtualenv=/home/openstates/virt{{ gitresult.after }}
  become_user: "openstates"
- name: install Pipfile.lock
  command: /home/openstates/virt{{ gitresult.after }}/bin/pipenv install # --deploy
  args:
    chdir: /home/openstates/src/openstates.org
  environment:
    VIRTUAL_ENV: /home/openstates/virt{{ gitresult.after }}
  become_user: "openstates"
- name: link virtualenv
  file: src=/home/openstates/virt{{ gitresult.after }} dest=/home/openstates/virt state=link
  notify:
    - restart django-application

# nginx
- name: make certs dir
  file: path=/etc/nginx/certs/ state=directory
- name: generate dh params
  command: openssl dhparam -out /etc/nginx/certs/dhparams.pem 2048 creates=/etc/nginx/certs/dhparams.pem
- name: remove nginx default config
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: write nginx template
  template: src=nginx.j2 dest=/etc/nginx/sites-enabled/openstates
  notify:
    - restart nginx
- name: ensure nginx is running and starts on boot
  service: name=nginx state=restarted enabled=yes

# new relic
- name: generate new relic config
  command: /home/openstates/virt/bin/newrelic-admin generate-config {{ newrelic_key }} /home/openstates/newrelic.ini creates=/home/openstates/newrelic.ini
- name: rename new relic app
  replace: dest=/home/openstates/newrelic.ini regexp='Python Application' replace='alpha.openstates.org'

# django
# - name: collectstatic
#   command: /home/openstates/virt/bin/python manage.py collectstatic --settings=openstates.settings --noinput chdir=/home/openstates/src/openstates.org
#   environment: '{{django_environment}}'

- name: migrate
  command: /home/openstates/virt/bin/python manage.py migrate --settings=openstates.settings --noinput chdir=/home/openstates/src/openstates.org
  environment: '{{django_environment}}'
- name: create Site
  command: echo "from django.contrib.sites.models import Site;Site.objects.get_or_create(domain='alpha.openstates.org', name='alpha.openstates.org')" | /home/openstates/virt/bin/python manage.py shell --settings=openstates.settings chdir=/home/openstates/src/openstates.org
  environment: '{{django_environment}}'
# TODO: add run of shapefiles/download.py
# - name: loadshapefiles
#   command: /home/openstates/virt/bin/python manage.py loadshapefiles --settings=openstates.settings chdir=/home/openstates/src/openstates.org
#   environment: '{{django_environment}}'
# - name: loadmappings
#   command: /home/openstates/virt/bin/python manage.py loadmappings --settings=openstates.settings chdir=/home/openstates/src/openstates.org
#   environment: '{{django_environment}}'

# uwsgi
- name: write uwsgi template
  template: src=uwsgi.j2 dest=/etc/uwsgi/apps-enabled/openstates.ini
  notify:
    - restart django-application
- name: start uwsgi
  service: name=uwsgi state=started
